[package]
name = "moscope"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.1.1"
serde_json = "1.0"
serde = { version = "1.0.228", features = ["derive"] }
regex = "1.12.2"
